### ISSUE TITLE
In Early Loading problem

### ISSUE THREAD

**Issue by Park-jaehyeon02** [Park-jaehyeon02/web_programming#3]
웹페이지를 초기에 불러올 때  페이지 height가 커지는 단점이 존재....
```css
@keyframes hide2show {
  from {
    opacity: 0;
  }

  50% {
    opacity: 0;
  }

  70% {
    opacity: 0.5;
  }

  to {
    opacity: 1;
  }
}
```
투명도를 이용해 보임/사라짐 이기 때문에 아마 content를 감싸는 내용들이 box가 작을 때는 한 글자씩 아래로 향하다가 box가 커지면 위로 돌아오면서 문제가 사라지는 듯...
-> 현재css만으로 해결하는 방법이 생각이 나지않음.
